version: "3.9"
services:

  go:
    build: ./go
    ports:
      - "8080:8080"
    networks:
      - some-net

  react:
    build: ./react
    ports:
      - "3000:3000"
    networks:
      - some-net
      
  postgres:
    image: postgres:10
    environment:
      POSTGRES_DB: "d8ha2ongbrinnm"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "5432:5432"
    volumes: 
      - ../2. Init Database:/docker-entrypoint-initdb.d
      - .:/var/lib/postgresql/data
    networks:
      - some-net

networks:
  some-net:
    driver: bridge